[package]
name = "blockchain"
version = "0.1.0"
authors = ["Grupo 2"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
std-semaphore = "0.1"
blake2 = "*"

[[bin]]
name = "app"
path = "src/main.rs"